config/routes.rb
Centralpoker::Application.routes.draw do
  resources :torneios

  match ':controller(/:action(/:id))(.:format)'
end

app/models/torneio.rb
class Torneio < ActiveRecord::Base
  attr_accessible :buyIn, :formato, :jogadoresPorMesa, :limite, :linkExterno, :moeda, :nome, :tipoPagamento, :velocidade
  
  validates_uniqueness_of :nome
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/torneios_controller.rb
class TorneiosController < ApplicationController
  # GET /torneios
  # GET /torneios.json
  def index
    @torneios = Torneio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @torneios }
    end
  end

  # GET /torneios/1
  # GET /torneios/1.json
  def show
    @torneio = Torneio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @torneio }
    end
  end

  # GET /torneios/new
  # GET /torneios/new.json
  def new
    @torneio = Torneio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @torneio }
    end
  end

  # GET /torneios/1/edit
  def edit
    @torneio = Torneio.find(params[:id])
  end

  # POST /torneios
  # POST /torneios.json
  def create
    @torneio = Torneio.new(params[:torneio])

    respond_to do |format|
      if @torneio.save
        format.html { redirect_to @torneio, notice: 'Torneio was successfully created.' }
        format.json { render json: @torneio, status: :created, location: @torneio }
      else
        format.html { render action: "new" }
        format.json { render json: @torneio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /torneios/1
  # PUT /torneios/1.json
  def update
    @torneio = Torneio.find(params[:id])

    respond_to do |format|
      if @torneio.update_attributes(params[:torneio])
        format.html { redirect_to @torneio, notice: 'Torneio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @torneio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /torneios/1
  # DELETE /torneios/1.json
  def destroy
    @torneio = Torneio.find(params[:id])
    @torneio.destroy

    respond_to do |format|
      format.html { redirect_to torneios_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/webget_controller.rb
class WebgetController < ApplicationController
  
  def pokerstars
    
    require 'net/http'
    require 'xmlsimple'
    
    @url = 'http://www.pokerstars.com/datafeed_global/tournaments/all.xml'
    @xml_data = Net::HTTP.get_response(URI.parse(@url)).body
    @ref  = XmlSimple.xml_in(@xml_data)
    
    @ref['tournament'].each do |torneio| 
      begin
        @save = Torneio.new
        @save.nome = torneio['name']
        @save.save(:validate => false)
      rescue
        
      end
    end

    respond_to do |format|
      format.xml { render :xml => @ref }
      format.json { render :json => @ref }
    end
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/torneios_helper.rb
module TorneiosHelper
end

app/helpers/webget_helper.rb
module WebgetHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Centralpoker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/torneios/_form.html.erb
<%= form_for(@torneio) do |f| %>
  <% if @torneio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@torneio.errors.count, "error") %> prohibited this torneio from being saved:</h2>

      <ul>
      <% @torneio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :limite %><br />
    <%= f.text_field :limite %>
  </div>
  <div class="field">
    <%= f.label :buyIn %><br />
    <%= f.text_field :buyIn %>
  </div>
  <div class="field">
    <%= f.label :tipoPagamento %><br />
    <%= f.text_field :tipoPagamento %>
  </div>
  <div class="field">
    <%= f.label :velocidade %><br />
    <%= f.text_field :velocidade %>
  </div>
  <div class="field">
    <%= f.label :moeda %><br />
    <%= f.text_field :moeda %>
  </div>
  <div class="field">
    <%= f.label :formato %><br />
    <%= f.text_field :formato %>
  </div>
  <div class="field">
    <%= f.label :jogadoresPorMesa %><br />
    <%= f.text_field :jogadoresPorMesa %>
  </div>
  <div class="field">
    <%= f.label :linkExterno %><br />
    <%= f.text_field :linkExterno %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/torneios/edit.html.erb
<h1>Editing torneio</h1>

<%= render 'form' %>

<%= link_to 'Show', @torneio %> |
<%= link_to 'Back', torneios_path %>

app/views/torneios/index.html.erb
<h1>Listing torneios</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Limite</th>
    <th>Buyin</th>
    <th>Tipopagamento</th>
    <th>Velocidade</th>
    <th>Moeda</th>
    <th>Formato</th>
    <th>Jogadorespormesa</th>
    <th>Linkexterno</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @torneios.each do |torneio| %>
  <tr>
    <td><%= torneio.nome %></td>
    <td><%= torneio.limite %></td>
    <td><%= torneio.buyIn %></td>
    <td><%= torneio.tipoPagamento %></td>
    <td><%= torneio.velocidade %></td>
    <td><%= torneio.moeda %></td>
    <td><%= torneio.formato %></td>
    <td><%= torneio.jogadoresPorMesa %></td>
    <td><%= torneio.linkExterno %></td>
    <td><%= link_to 'Show', torneio %></td>
    <td><%= link_to 'Edit', edit_torneio_path(torneio) %></td>
    <td><%= link_to 'Destroy', torneio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Torneio', new_torneio_path %>

app/views/torneios/new.html.erb
<h1>New torneio</h1>

<%= render 'form' %>

<%= link_to 'Back', torneios_path %>

app/views/torneios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @torneio.nome %>
</p>

<p>
  <b>Limite:</b>
  <%= @torneio.limite %>
</p>

<p>
  <b>Buyin:</b>
  <%= @torneio.buyIn %>
</p>

<p>
  <b>Tipopagamento:</b>
  <%= @torneio.tipoPagamento %>
</p>

<p>
  <b>Velocidade:</b>
  <%= @torneio.velocidade %>
</p>

<p>
  <b>Moeda:</b>
  <%= @torneio.moeda %>
</p>

<p>
  <b>Formato:</b>
  <%= @torneio.formato %>
</p>

<p>
  <b>Jogadorespormesa:</b>
  <%= @torneio.jogadoresPorMesa %>
</p>

<p>
  <b>Linkexterno:</b>
  <%= @torneio.linkExterno %>
</p>


<%= link_to 'Edit', edit_torneio_path(@torneio) %> |
<%= link_to 'Back', torneios_path %>